### ISSUE TITLE
error casting date from string to Date in mongoose

### ISSUE THREAD

**Issue by kapil1garg** [NUDelta/interactive-soap-notes#28]
```
[interactive-soap-notes] [2024-03-04 16:49:12]   reason: CastError: Cast to date failed for value "Mon, Mar 4, 2024 at 10:47 AM" (type string) at path "date"
[interactive-soap-notes] [2024-03-04 16:49:12]       at SchemaDate.cast (/workspace/node_modules/mongoose/lib/schema/date.js:376:11)
[interactive-soap-notes] [2024-03-04 16:49:12]       at SchemaType.applySetters (/workspace/node_modules/mongoose/lib/schemaType.js:1221:12)
[interactive-soap-notes] [2024-03-04 16:49:12]       at SingleNested.$set (/workspace/node_modules/mongoose/lib/document.js:1418:22)
[interactive-soap-notes] [2024-03-04 16:49:12]       at SingleNested.$set (/workspace/node_modules/mongoose/lib/document.js:1115:16)
[interactive-soap-notes] [2024-03-04 16:49:12]       at SingleNested.Document (/workspace/node_modules/mongoose/lib/document.js:166:12)
[interactive-soap-notes] [2024-03-04 16:49:12]       at SingleNested.Subdocument (/workspace/node_modules/mongoose/lib/types/subdocument.js:34:12)
[interactive-soap-notes] [2024-03-04 16:49:12]       at new SingleNested (/workspace/node_modules/mongoose/lib/schema/subdocument.js:78:21)
[interactive-soap-notes] [2024-03-04 16:49:12]       at SchemaSubdocument.cast (/workspace/node_modules/mongoose/lib/schema/subdocument.js:193:12)
[interactive-soap-notes] [2024-03-04 16:49:12]       at SchemaType.applySetters (/workspace/node_modules/mongoose/lib/schemaType.js:1221:12)
[interactive-soap-notes] [2024-03-04 16:49:12]       at EmbeddedDocument.$set (/workspace/node_modules/mongoose/lib/document.js:1418:22) {
[interactive-soap-notes] [2024-03-04 16:49:12]     stringValue: '"Mon, Mar 4, 2024 at 10:47 AM"',
[interactive-soap-notes] [2024-03-04 16:49:12]     messageFormat: undefined,
[interactive-soap-notes] [2024-03-04 16:49:12]     kind: 'date',
[interactive-soap-notes] [2024-03-04 16:49:12]     value: 'Mon, Mar 4, 2024 at 10:47 AM',
[interactive-soap-notes] [2024-03-04 16:49:12]     path: 'date',
```

Seems to work fine for SOAP notes, but the front-ends sends up a `Date` object for that:
```
// hold a last updated timestamp
const lastUpdated = new Date();
...
let dataToSave = {
...
 lastUpdated: lastUpdated,
...
};
```

**Comment by kapil1garg** [comment]
omg it's breaking in Safari and not Chrome: 
<img width="2816" alt="image" src="https://github.com/NUDelta/interactive-soap-notes/assets/3069370/19d68a42-a34b-4b1a-ab17-4fc4229cf969">

Notice the "at" in the last updated date and the test3 date

**Comment by kapil1garg** [comment]
thread on date serialization for nextjs: 
- https://stackoverflow.com/questions/70449092/reason-object-object-date-cannot-be-serialized-as-json-please-only-ret

This plugin might be helpful: https://github.com/blitz-js/next-superjson-plugin

**Comment by kapil1garg** [comment]
it also appears that safari can parse it's own format: 
<img width="435" alt="image" src="https://github.com/NUDelta/interactive-soap-notes/assets/3069370/46d4caee-dd7a-4020-93d2-1129667da569">

so another option might be to have the front-end parse everything into a date object before sending it up to the server
